### ISSUE TITLE
Incorrect spacing between index numbers

### ISSUE THREAD

**Issue by DanielFlaum** [blissymbolics/blissymbols#9]
I realize this project hasn't been touched in awhile, but I thought I'd add it in case it ever revives.

The Blissviewer does not put correct spacing between adjacent digits numbers (i.e. BCI-AV# 8496-8504). [The Fundamental Rules of Blissymbolics](https://www.blissymbolics.org/images/bliss-fundamental-rules-2020-06-16.pdf) specifies on page 6 (page 7 of the PDF) that "the width is 1⁄8 of a matrix square between two digits". This is illustrated in a figure immediately below the containing paragraph.

Instead of 1⁄8, the Blissviewer puts 1⁄4 of a space, as seen here (Blissymbol for money added to show height of full matrix square):

![image](https://user-images.githubusercontent.com/11306526/234415913-2dc0e085-b840-4625-ab84-78cf3ce3a250.png)

In the above figure, the space between the two digits should be halved.

This appears to me to be a bug, since [these lines](https://github.com/blissymbolics/blissymbols/blob/7c49c2f4987dc75820b3f5f36df2d2cf56902c2c/blissviewer.ts#L272-L273) appear to be intended to do exactly this.

**Comment by heatherleaf** [comment]
Thanks for this, it was a bug as you suspected! Fixed in 26a16c038428893b88b94baff906683a2602d019

(Yes, this project is not very active but this was a simple fix)
